/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.core.zperf.ui.charts;

import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Jefferson Fermo <jefffermo@yahoo.com>
 */
public class AverageThoughputChartUi extends javax.swing.JPanel {

    /**
     * Creates new form BarChartPanel
     */
    public AverageThoughputChartUi() {
        initComponents();        
        
    }

    public AverageThoughputChartUi(String title){
        
        initComponents();   
        
//        averageThroughputDataSet.addValue(10, "Average", "TEST1");
//        averageThroughputDataSet.addValue(15, "Average", "TEST2");
//        averageThroughputDataSet.addValue(30, "Average", "TEST3");
        
        barChart.setDataset(averageThroughputDataSet);
        
//        barChart.se
    }
        
    public void addSpeed(double speed, String traceName){
        averageThroughputDataSet.addValue(speed, "Average", traceName);
        
    }
    
    public void setTitle(double percentage){
        
        barChart.setValueAxisLabel("Throuput(Mbps) @ " + percentage + "%");
        
                
    }
    
    public void clearChart(){
        averageThroughputDataSet.clear();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        barChart = new org.jfree.beans.JBarChart();

        barChart.setCategoryAxisLabel(org.openide.util.NbBundle.getMessage(AverageThoughputChartUi.class, "AverageThoughputChartUi.barChart.categoryAxisLabel")); // NOI18N
        barChart.setCategoryAxisLocation(org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT);
        barChart.setOrientation(org.jfree.chart.plot.PlotOrientation.HORIZONTAL);
        barChart.setSource(org.openide.util.NbBundle.getMessage(AverageThoughputChartUi.class, "AverageThoughputChartUi.barChart.source")); // NOI18N
        barChart.setSubtitle(org.openide.util.NbBundle.getMessage(AverageThoughputChartUi.class, "AverageThoughputChartUi.barChart.subtitle")); // NOI18N
        barChart.setTitle(org.openide.util.NbBundle.getMessage(AverageThoughputChartUi.class, "AverageThoughputChartUi.barChart.title")); // NOI18N
        barChart.setValueAxisLabel(org.openide.util.NbBundle.getMessage(AverageThoughputChartUi.class, "AverageThoughputChartUi.barChart.valueAxisLabel")); // NOI18N

        javax.swing.GroupLayout barChartLayout = new javax.swing.GroupLayout(barChart);
        barChart.setLayout(barChartLayout);
        barChartLayout.setHorizontalGroup(
            barChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        barChartLayout.setVerticalGroup(
            barChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(barChart);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jfree.beans.JBarChart barChart;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    //private org.jfree.beans.JBarChart chart;
    DefaultCategoryDataset averageThroughputDataSet = new DefaultCategoryDataset();

}
