/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.core.zperf.ui.charts;

import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Jefferson Fermo <jefffermo@yahoo.com>
 */
public class AverageThoughputChartUi extends javax.swing.JPanel {

    /**
     * Creates new form BarChartPanel
     */
    public AverageThoughputChartUi() {
        initComponents();
        
        
    }

    public AverageThoughputChartUi(String title){
        barChart.setDataset(averageThroughputDataSet);
    }
        
    public void addSpeed(double speed, String traceName){
        averageThroughputDataSet.addValue(speed, "Average", traceName);
        
        //barChart.chartChanged(null);
        
    }
    
    public void clearChart(){
        averageThroughputDataSet.clear();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barChart = new org.jfree.beans.JBarChart();

        barChart.setCategoryAxisLabel(org.openide.util.NbBundle.getMessage(AverageThoughputChartUi.class, "AverageThoughputChartUi.barChart.categoryAxisLabel")); // NOI18N
        barChart.setLegendPosition(org.jfree.beans.LegendPosition.NONE);
        barChart.setSource(org.openide.util.NbBundle.getMessage(AverageThoughputChartUi.class, "AverageThoughputChartUi.barChart.source")); // NOI18N
        barChart.setSubtitle(org.openide.util.NbBundle.getMessage(AverageThoughputChartUi.class, "AverageThoughputChartUi.barChart.subtitle")); // NOI18N
        barChart.setTitle(org.openide.util.NbBundle.getMessage(AverageThoughputChartUi.class, "AverageThoughputChartUi.barChart.title")); // NOI18N
        barChart.setValueAxisLabel(org.openide.util.NbBundle.getMessage(AverageThoughputChartUi.class, "AverageThoughputChartUi.barChart.valueAxisLabel")); // NOI18N

        javax.swing.GroupLayout barChartLayout = new javax.swing.GroupLayout(barChart);
        barChart.setLayout(barChartLayout);
        barChartLayout.setHorizontalGroup(
            barChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        barChartLayout.setVerticalGroup(
            barChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barChart, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barChart, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jfree.beans.JBarChart barChart;
    // End of variables declaration//GEN-END:variables

    DefaultCategoryDataset averageThroughputDataSet = new DefaultCategoryDataset();

}
