/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.core.zperf.ui.charts;

import info.monitorenter.gui.chart.Chart2D;
import info.monitorenter.gui.chart.IAxis;
import info.monitorenter.gui.chart.axis.scalepolicy.AxisScalePolicyManualTicks;
import info.monitorenter.gui.chart.views.ChartPanel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JScrollPane;

/**
 *
 * @author core
 */
public class ZapCCDFChartPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChartPanel
     */
    public ZapCCDFChartPanel() {
        initComponents();
    }    
    
    public ZapCCDFChartPanel(String name){
        
        this.setName(name);
        
        setLayout(new BorderLayout());
        
        zapCCDFChart = new Chart2D();
        
        zapCCDFChart.getAxisX().setPaintGrid(true);
        zapCCDFChart.getAxisY().setPaintGrid(true);
        zapCCDFChart.getAxisX().setAxisTitle(new IAxis.AxisTitle("Percentage"));
        zapCCDFChart.setToolTipType(Chart2D.ToolTipType.VALUE_SNAP_TO_TRACEPOINTS);
        
        @SuppressWarnings("unchecked")
        IAxis<AxisScalePolicyManualTicks> xAxis = (IAxis<AxisScalePolicyManualTicks>) zapCCDFChart.getAxisX();
        xAxis.setAxisScalePolicy(new AxisScalePolicyManualTicks()); 
        
        xAxis.setMajorTickSpacing(100);
        xAxis.setMinorTickSpacing(5);
        xAxis.setStartMajorTick(true);
        
        zapCCDFChart.setPreferredSize(new Dimension(800, 400));
        
        ChartPanel chartPanel = new ChartPanel(zapCCDFChart);
        
        JScrollPane scrollPane = new JScrollPane();
        
        scrollPane.setViewportView(chartPanel);
        
        add(scrollPane);
    }
    /**
     * @return the zapCCDFChart
     */
    public Chart2D getZapCCDFChart() {
        return zapCCDFChart;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zapCCDFChart = new info.monitorenter.gui.chart.Chart2D();

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout zapCCDFChartLayout = new javax.swing.GroupLayout(zapCCDFChart);
        zapCCDFChart.setLayout(zapCCDFChartLayout);
        zapCCDFChartLayout.setHorizontalGroup(
            zapCCDFChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        zapCCDFChartLayout.setVerticalGroup(
            zapCCDFChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(zapCCDFChart, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private info.monitorenter.gui.chart.Chart2D zapCCDFChart;
    // End of variables declaration//GEN-END:variables

    
}
