/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.core.zperf.ui.charts;

import info.monitorenter.gui.chart.Chart2D;
import info.monitorenter.gui.chart.ITrace2D;
import info.monitorenter.gui.chart.traces.Trace2DLtd;
import info.monitorenter.gui.chart.views.ChartPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JScrollPane;
import org.core.zperf.zap.Measurement;

/**
 *
 * @author core
 */
public class ZPerfChartUi extends java.awt.Panel {

    /**
     * Creates new form zPerfChartUi
     */
//    public ZPerfChartUi() {
//        initComponents();
//    }

    public ZPerfChartUi(){
        initComponents();        
        
    }
    
    public ZPerfChartUi(String title){
        
        setLayout(new BorderLayout());
        
        zperfChart = new Chart2D();
        
        initComponents();
        
        averageThroughputTrace.setColor(Color.RED);
        averageThroughputTrace.setName("Average Throughput");
        _0thPercentileTrace.setColor(Color.DARK_GRAY);
        _0thPercentileTrace.setName("0%");
        _50thPercentileTrace.setColor(Color.GREEN);
        _50thPercentileTrace.setName("50%");
        _90thPercentileTrace.setColor(Color.MAGENTA);
        _90thPercentileTrace.setName("90%");
        _95thPercentileTrace.setColor(Color.ORANGE);
        _95thPercentileTrace.setName("95%");
        _99thPercentileTrace.setColor(Color.BLUE);
        _99thPercentileTrace.setName("99%");
        _99_9thPercentileTrace.setColor(Color.YELLOW);
        _99_9thPercentileTrace.setName("99.9%");
        
        zperfChart.addTrace(averageThroughputTrace);
        zperfChart.addTrace(_0thPercentileTrace);
        zperfChart.addTrace(_50thPercentileTrace);
        zperfChart.addTrace(_90thPercentileTrace);
        zperfChart.addTrace(_95thPercentileTrace);
        zperfChart.addTrace(_99thPercentileTrace);
        zperfChart.addTrace(_99_9thPercentileTrace);
        
        ChartPanel chartPanel = new ChartPanel(zperfChart);
        
        JScrollPane scrollPane = new JScrollPane();
        
        scrollPane.setViewportView(chartPanel);
        
        add(scrollPane);
    }
    
    public void addNewMeasurementToTrace(Measurement measurement){
        averageThroughputTrace.addPoint((double) measurement.getBurstTestNumber(), measurement.getTotalAggregateThoroughput());
        _0thPercentileTrace.addPoint((double) measurement.getBurstTestNumber(), measurement.get0thPercentile());
        _50thPercentileTrace.addPoint((double) measurement.getBurstTestNumber(), measurement.get50thPercentile());
        _90thPercentileTrace.addPoint((double) measurement.getBurstTestNumber(), measurement.get90thPercentile());
        _95thPercentileTrace.addPoint((double) measurement.getBurstTestNumber(), measurement.get95thPercentile());
        _99thPercentileTrace.addPoint((double) measurement.getBurstTestNumber(), measurement.get99thPercentile());
        _99_9thPercentileTrace.addPoint((double) measurement.getBurstTestNumber(), measurement.get99_9thPercentile());
        
    }
    
    public void clearAllTraces(){
        averageThroughputTrace.removeAllPoints();
        _0thPercentileTrace.removeAllPoints();
        _50thPercentileTrace.removeAllPoints();
        _90thPercentileTrace.removeAllPoints();
        _95thPercentileTrace.removeAllPoints();
        _99thPercentileTrace.removeAllPoints();
        _99_9thPercentileTrace.removeAllPoints();
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zperfChart = new info.monitorenter.gui.chart.Chart2D();

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout zperfChartLayout = new javax.swing.GroupLayout(zperfChart);
        zperfChart.setLayout(zperfChartLayout);
        zperfChartLayout.setHorizontalGroup(
            zperfChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
        );
        zperfChartLayout.setVerticalGroup(
            zperfChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );

        add(zperfChart, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private info.monitorenter.gui.chart.Chart2D zperfChart;
    // End of variables declaration//GEN-END:variables

    private ITrace2D averageThroughputTrace = new Trace2DLtd(200); 
    private ITrace2D _0thPercentileTrace = new Trace2DLtd(200); 
    private ITrace2D _50thPercentileTrace = new Trace2DLtd(200); 
    private ITrace2D _90thPercentileTrace = new Trace2DLtd(200); 
    private ITrace2D _95thPercentileTrace = new Trace2DLtd(200); 
    private ITrace2D _99thPercentileTrace = new Trace2DLtd(200); 
    private ITrace2D _99_9thPercentileTrace = new Trace2DLtd(200);
}
